# Generated by Django 4.2.7 on 2023-12-26 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 12, 26, 4, 52, 17, 342991, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
