# Generated by Django 4.2.7 on 2023-12-26 05:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0002_user_birthday_user_city_user_country_user_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 12, 26, 5, 7, 25, 330531, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(max_length=50)),
                ('body', models.TextField()),
                ('publish_date', models.DateField(default=datetime.datetime(2023, 12, 26, 5, 7, 25, 331870, tzinfo=datetime.timezone.utc))),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('replyIDs', models.TextField()),
                ('authorid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(max_length=30)),
                ('body', models.TextField()),
                ('publish_date', models.DateField(default=datetime.datetime(2023, 12, 26, 5, 7, 25, 331659, tzinfo=datetime.timezone.utc))),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('commentIDs', models.TextField()),
                ('authorid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
