# Generated by Django 4.2.7 on 2023-12-29 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0003_alter_user_birthday_comments_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 29, 6, 16, 17, 388497, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 29, 6, 16, 17, 388711, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 12, 29, 6, 16, 17, 387425, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
