# Generated by Django 4.2.7 on 2024-01-24 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0006_remove_user_followers_alter_blog_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 24, 10, 27, 32, 81754, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 24, 10, 27, 32, 81965, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2024, 1, 24, 10, 27, 32, 80723, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
