# Generated by Django 4.2.7 on 2024-02-05 11:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0012_alter_blog_publish_date_alter_comments_publish_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='commentIDs',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='heading',
        ),
        migrations.AddField(
            model_name='comments',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogsite.blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 5, 11, 38, 45, 351379, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 5, 11, 38, 45, 351586, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2024, 2, 5, 11, 38, 45, 350357, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
