# Generated by Django 4.2.7 on 2024-02-05 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0013_remove_blog_commentids_remove_comments_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='replyIDs',
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 5, 13, 32, 28, 117462, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 5, 13, 32, 28, 117663, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2024, 2, 5, 13, 32, 28, 116418, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
