# Generated by Django 4.2.7 on 2024-02-20 11:41

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0017_alter_blog_publish_date_alter_comments_publish_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='fwr',
        ),
        migrations.AddField(
            model_name='follower',
            name='flw',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 20, 11, 41, 52, 965750, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 20, 11, 41, 52, 965998, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='replies',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 20, 11, 41, 52, 966229, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2024, 2, 20, 11, 41, 52, 964708, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
