# Generated by Django 4.2.7 on 2024-03-11 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0021_alter_blog_publish_date_alter_comments_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 11, 12, 35, 41, 303711, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 11, 12, 35, 41, 303965, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='replies',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 11, 12, 35, 41, 304184, tzinfo=datetime.timezone.utc)),
        ),
    ]
